### YamlMime:OData
uid: Microsoft.Dynamics.CRM.ApiSettings
name: "ApiSettings"
type: solution
metadata: 
  title: "Common Data Service ApiSettings Solution Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: fb5fb75d-f8a6-4509-8a0f-c70737502915
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Common Data Service ApiSettings Solution."
namespace: Microsoft.Dynamics.CRM
header:
# This solution has no description.
 unique_name: ApiSettings
 version: "1.0.0.13"
 customization_prefix: default
entities:
  description: "The following entities are included in this solution."
  entity_items:
   - type: Microsoft.Dynamics.CRM.apisettings
     description: "This entity contains the mapping of entity to the mode with which bulk apis are executed"
# This solution includes no actions.
# There are no remarks for this solution.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex