### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_Playbook
name: "Playbook"
type: solution
metadata: 
  title: "Common Data Service Playbook Solution Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 0c424798-fbe7-4fc7-8b2f-60e901237ed6
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Common Data Service Playbook Solution."
namespace: Microsoft.Dynamics.CRM
header:
 description: "Playbook"
 unique_name: msdyn_Playbook
 version: "9.0.2012.2000 "
 customization_prefix: msdyn
entities:
  description: "The following entities are included in this solution."
  entity_items:
   - type: Microsoft.Dynamics.CRM.msdyn_callablecontext
     description: ""
   - type: Microsoft.Dynamics.CRM.msdyn_playbookactivity
     description: "Stores the details of the activities to be created when a playbook is launched."
   - type: Microsoft.Dynamics.CRM.msdyn_playbookactivityattribute
     description: "Stores attribute names and values of the playbook activity."
   - type: Microsoft.Dynamics.CRM.msdyn_playbookcategory
     description: "List of categories for which a playbook can be created."
   - type: Microsoft.Dynamics.CRM.msdyn_playbookinstance
     description: "Actual instance of a playbook template once it is launched."
   - type: Microsoft.Dynamics.CRM.msdyn_playbooktemplate
     description: "Playbook templates contains the definition of the Playbook that helps to standardize a set of best practices or next best actions."
# This solution includes no actions.
# There are no remarks for this solution.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex