### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_ImageConfiguration
name: "Image Configuration"
type: solution
metadata: 
  title: "Microsoft Dataverse Image Configuration Solution Reference | MicrosoftDocs"
  ms.date: "06/02/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 1ec3a459-7c3a-49b9-946d-b55076728ee0
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Microsoft Dataverse Image Configuration Solution."
namespace: Microsoft.Dynamics.CRM
header:
# This solution has no description.
 unique_name: msdyn_ImageConfiguration
 version: "1.0.0.6"
 customization_prefix: default
entities:
  description: "The following entities are included in this solution."
  entity_items:
   - type: Microsoft.Dynamics.CRM.attributeimageconfig
     description: "Store configuration for each image attribute"
   - type: Microsoft.Dynamics.CRM.entityimageconfig
     description: "Store image configuration for each entity"
# This solution includes no actions.
# There are no remarks for this solution.
href_see_also:
- text: "Use the Microsoft Dataverse Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex