### YamlMime:OData
uid: Microsoft.Dynamics.CRM.S2SApplicationExtension
name: "S2SApplicationExtension"
type: solution
metadata: 
  title: "Dataverse S2SApplicationExtension Solution Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: c1825cf2-6594-4a80-a01e-c64ca1efd122
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse S2SApplicationExtension Solution."
namespace: Microsoft.Dynamics.CRM
header:
 description: "S2SApplicationExtension Solution"
 unique_name: S2SApplicationExtension
 version: "1.0.0.0"
 customization_prefix: default
entities:
  description: "The following entities are included in this solution."
  entity_items:
   - type: Microsoft.Dynamics.CRM.systemuser
     description: "Person with access to the Microsoft CRM system and who owns objects in the Microsoft CRM database."
# This solution includes no actions.
# There are no remarks for this solution.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex