### YamlMime:OData
uid: Microsoft.Dynamics.CRM.GetDistinctValuesImportFileResponse
name: "GetDistinctValuesImportFileResponse"
type: complextype
metadata: 
  title: "Microsoft Dataverse GetDistinctValuesImportFileResponse ComplexType Reference | MicrosoftDocs"
  ms.date: "06/02/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 11dfbbc6-4e70-4c72-b546-883831747046
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Microsoft Dataverse Web API GetDistinctValuesImportFileResponse ComplexType."
namespace: Microsoft.Dynamics.CRM
# This complex type doesn't inherit from another complextype.
description: "The response from the GetDistinctValuesImportFile function. " 
properties:
  description: "The properties of a complex type contain the structured data of the type."
  property_items:
  - name: Values
    type: Edm.String
    nullable: false
    unicode: false
    description: "The distinct values for a column in the source file. "
    iscollection: true
# This complex type doesn't have any navigation properties.
usedby:
  description: "The following use the GetDistinctValuesImportFileResponse ComplexType."
  usedby_items:
  - name: Microsoft.Dynamics.CRM.GetDistinctValuesImportFile
    used_as: ReturnType
# There are no remarks for this complex type.
href_see_also:
- text: "Use the Microsoft Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex
