### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_RetrieveKPIvaluesfromDCIResponse
name: "msdyn_RetrieveKPIvaluesfromDCIResponse"
type: complextype
metadata: 
  title: "Dataverse msdyn_RetrieveKPIvaluesfromDCIResponse ComplexType Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: a2f5b2b7-3c45-46e5-902f-076ef782de8f
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse Web API msdyn_RetrieveKPIvaluesfromDCIResponse ComplexType."
namespace: Microsoft.Dynamics.CRM
# This complex type doesn't inherit from another complextype.
description: "" 
properties:
  description: "The properties of a complex type contain the structured data of the type."
  property_items:
  - name: KPIValues
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
    iscollection: false
  - name: Errors
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
    iscollection: false
# This complex type doesn't have any navigation properties.
usedby:
  description: "The following use the msdyn_RetrieveKPIvaluesfromDCIResponse ComplexType."
  usedby_items:
  - name: Microsoft.Dynamics.CRM.msdyn_RetrieveKPIvaluesfromDCI
    used_as: ReturnType
# There are no remarks for this complex type.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex
