### YamlMime:OData
uid: Microsoft.Dynamics.CRM.ValidateAIConfigurationResponse
name: "ValidateAIConfigurationResponse"
type: complextype
metadata: 
  title: "Microsoft Dataverse ValidateAIConfigurationResponse ComplexType Reference | MicrosoftDocs"
  ms.date: "04/12/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: e83b28ac-b354-4e23-a410-cca7bea38638
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Microsoft Dataverse Web API ValidateAIConfigurationResponse ComplexType."
namespace: Microsoft.Dynamics.CRM
# This complex type doesn't inherit from another complextype.
description: "" 
properties:
  description: "The properties of a complex type contain the structured data of the type."
  property_items:
  - name: result
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
    iscollection: false
# This complex type doesn't have any navigation properties.
usedby:
  description: "The following use the ValidateAIConfigurationResponse ComplexType."
  usedby_items:
  - name: Microsoft.Dynamics.CRM.ValidateAIConfiguration
    used_as: ReturnType
# There are no remarks for this complex type.
href_see_also:
- text: "Use the Microsoft Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex
