### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_iotdevicevisualizationconfiguration
name: "msdyn_iotdevicevisualizationconfiguration"
type: entitytype
metadata: 
  title: "Common Data Service EntityType Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: f7a76aba-ff47-4324-949c-5b8d4d0df1ad
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Common Data Service msdyn_iotdevicevisualizationconfiguration entitytype."
description: "IoT Device Visualization Configuration"
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_iotdevicevisualizationconfigurations"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: IoT Device Visualization Configuration
  primary_key: msdyn_iotdevicevisualizationconfigurationid
  primary_name_attribute: msdyn_name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_actionname
      type: Edm.String
      display_name: "Action Name"
      description: "Action name for IoT device visualization"
      iscomputed: false
      isreadonly: false
    - name: msdyn_aggregation
      type: Edm.Int32
      display_name: "Aggregation"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 192350000
          label: "None"
        - value: 192350001
          label: "Avg"
        - value: 192350002
          label: "Min"
        - value: 192350003
          label: "Max"
        - value: 192350004
          label: "Sum"
        - value: 192350005
          label: "Count"
    - name: msdyn_deviceevent
      type: Edm.Int32
      display_name: "Device Event"
      description: "Device Event of device visualization"
      iscomputed: false
      isreadonly: false
      options:
        - value: 192350000
          label: "IoT Alert"
        - value: 192350001
          label: "Case"
        - value: 192350002
          label: "Work Order"
    - name: msdyn_iotdevicevisualizationconfigurationid
      type: Edm.Guid
      display_name: "IoT Device Visualization Configuration"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: msdyn_name
      type: Edm.String
      display_name: "Name"
      description: "The name of the custom entity."
      iscomputed: false
      isreadonly: false
    - name: msdyn_position
      type: Edm.Int32
      display_name: "Position"
      description: "Position of device visualization"
      iscomputed: false
      isreadonly: false
    - name: msdyn_timerangetype
      type: Edm.Int32
      display_name: "Time Range Type"
      description: "Time range unit for device visualization"
      iscomputed: false
      isreadonly: false
      options:
        - value: 192350000
          label: "Hours"
        - value: 192350001
          label: "Days"
        - value: 192350002
          label: "Latest"
    - name: msdyn_timerangevalue
      type: Edm.Int32
      display_name: "Time Range Value"
      description: "Time range value for device visualization"
      iscomputed: false
      isreadonly: false
    - name: msdyn_visualizationconfigurationtype
      type: Edm.Int32
      display_name: "Visualization Configuration Type"
      description: "Visualization Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 192350000
          label: "Configuration 1"
        - value: 192350001
          label: "Configuration 2"
        - value: 192350002
          label: "Configuration 3"
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the IoT Device Visualization Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the IoT Device Visualization Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _msdyn_iotdevice_value
    single_valued_navigation_property:
    - msdyn_IoTDevice
    description: "Visualizations shown for this device"
  - name: _msdyn_iotdevicecategory_value
    single_valued_navigation_property:
    - msdyn_IoTDeviceCategory
    description: "Visualization shown for this device category"
  - name: _msdyn_measurement_value
    single_valued_navigation_property:
    - msdyn_Measurement
    description: "Property Definition"
  - name: _ownerid_value
    single_valued_navigation_property:
    - ownerid
    description: "Owner Id"
  - name: _owningbusinessunit_value
    single_valued_navigation_property:
    - owningbusinessunit
    description: "Unique identifier for the business unit that owns the record"
  - name: _owningteam_value
    single_valued_navigation_property:
    - owningteam
    description: "Unique identifier for the team that owns the record."
  - name: _owninguser_value
    single_valued_navigation_property:
    - owninguser
    description: "Unique identifier for the user that owns the record."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_iotdevicevisualizationconfiguration_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_iotdevicevisualizationconfiguration_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_iotdevicevisualizationconfiguration_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_iotdevicevisualizationconfiguration_modifiedonbehalfby
  - name: msdyn_IoTDevice
    type: Microsoft.Dynamics.CRM.msdyn_iotdevice
    partner: msdyn_iotdevicevisualizationconfiguration_iotdevice
  - name: msdyn_IoTDeviceCategory
    type: Microsoft.Dynamics.CRM.msdyn_iotdevicecategory
    partner: msdyn_iotdevicevisualizationconfiguration_iotdevicecategory
  - name: msdyn_Measurement
    type: Microsoft.Dynamics.CRM.msdyn_iotpropertydefinition
    partner: msdyn_iotdevicevisualizationconfiguration_measurement
  - name: ownerid
    type: Microsoft.Dynamics.CRM.principal
    partner: owner_msdyn_iotdevicevisualizationconfiguration
  - name: owningbusinessunit
    type: Microsoft.Dynamics.CRM.businessunit
    partner: business_unit_msdyn_iotdevicevisualizationconfiguration
  - name: owningteam
    type: Microsoft.Dynamics.CRM.team
    partner: team_msdyn_iotdevicevisualizationconfiguration
  - name: owninguser
    type: Microsoft.Dynamics.CRM.systemuser
    partner: user_msdyn_iotdevicevisualizationconfiguration
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_iotdevicevisualizationconfiguration_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_iotdevicevisualizationconfiguration
  - name: msdyn_iotdevicevisualizationconfiguration_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_iotdevicevisualizationconfiguration
  - name: msdyn_iotdevicevisualizationconfiguration_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_msdyn_iotdevicevisualizationconfiguration
  - name: msdyn_iotdevicevisualizationconfiguration_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_msdyn_iotdevicevisualizationconfiguration
  - name: msdyn_iotdevicevisualizationconfiguration_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_iotdevicevisualizationconfiguration
  - name: msdyn_iotdevicevisualizationconfiguration_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_iotdevicevisualizationconfiguration
  - name: msdyn_iotdevicevisualizationconfiguration_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_iotdevicevisualizationconfiguration
  - name: msdyn_iotdevicevisualizationconfiguration_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_iotdevicevisualizationconfiguration
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_iotdevicevisualizationconfiguration entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.GrantAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.ModifyAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrievePrincipalAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrieveSharedPrincipalsAndAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RevokeAccess
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the msdyn_iotdevicevisualizationconfiguration entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.IoTConnector
    description: "Enables IoT scenarios in Dynamics 365."
# There are no remarks for this entity.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex