### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_forecastconfiguration
name: "msdyn_forecastconfiguration"
type: entitytype
metadata: 
  title: "Dataverse EntityType Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 4a881568-7f9a-4260-b6b1-b51b92583d18
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse msdyn_forecastconfiguration entitytype."
# This entity doesn't have a description
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_forecastconfigurations"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Forecast Configuration
  primary_key: msdyn_forecastconfigurationid
  primary_name_attribute: msdyn_name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_additionalfilter
      type: Edm.String
      display_name: "Additional filters"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_advancedsettings
      type: Edm.String
      display_name: "Settings"
      description: "Forecast configuration settings"
      iscomputed: false
      isreadonly: false
    - name: msdyn_columns
      type: Edm.String
      display_name: "Columns"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_enddate
      type: Edm.DateTimeOffset
      display_name: "End Date"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_errormessage
      type: Edm.String
      display_name: "Error message"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_forecastcategoryattribute
      type: Edm.String
      display_name: "Forecast category attribute"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_forecastconfigurationid
      type: Edm.Guid
      display_name: "Forecast configuration id"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: msdyn_forecasttimezone
      type: Edm.String
      display_name: "Prefered timezone governing the scheduler of forecast snapshot"
      description: "Prefered timezone governing the scheduler of forecast snapshot"
      iscomputed: false
      isreadonly: false
    - name: msdyn_hierarchyentity
      type: Edm.String
      display_name: "Hierarchy entity"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_hierarchyrelationship
      type: Edm.String
      display_name: "Relationship"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_issnapshotscheduled
      type: Edm.Boolean
      display_name: "Enable Snapshot Scheduling"
      description: "Enable scheduling for forecast snapshots"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_name
      type: Edm.String
      display_name: "Forecast configuration name"
      description: "The name of the custom entity."
      iscomputed: false
      isreadonly: false
    - name: msdyn_numberofrecurrences
      type: Edm.Int32
      display_name: "Number of recurrences"
      description: "Indicate the number of recurrences that the forecast will be generated."
      iscomputed: false
      isreadonly: false
    - name: msdyn_periodtype
      type: Edm.Int32
      display_name: "Forecast period"
      description: "Select the type of period for which the forecast must be generated."
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Monthly"
        - value: 1
          label: "Quarterly"
    - name: msdyn_permissionsdata
      type: Edm.String
      display_name: "Permissions"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_pivots
      type: Edm.String
      display_name: "Pivots"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_publisheddatetime
      type: Edm.DateTimeOffset
      display_name: "Published date time"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_rollupdefaultviewid
      type: Edm.String
      display_name: "Rollup entity default view"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_rollupentity
      type: Edm.String
      display_name: "Rollup entity"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_rootentityrecordid
      type: Edm.String
      display_name: "Root record Id"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_snapshotschedule
      type: Edm.String
      display_name: "Schedule governing the forecast snapshot"
      description: "Schedule governing the forecast snapshot"
      iscomputed: false
      isreadonly: false
    - name: msdyn_startdate
      type: Edm.DateTimeOffset
      display_name: "Start Date"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_startingfiscalmonth
      type: Edm.Int32
      display_name: "Starting Fiscal month"
      description: "Select the fiscal month for the forecast configuration."
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "January"
        - value: 1
          label: "February"
        - value: 2
          label: "March"
        - value: 3
          label: "April"
        - value: 4
          label: "May"
        - value: 5
          label: "June"
        - value: 6
          label: "July"
        - value: 7
          label: "August"
        - value: 8
          label: "September"
        - value: 9
          label: "October"
        - value: 10
          label: "November"
        - value: 11
          label: "December"
    - name: msdyn_startingfiscalquarter
      type: Edm.Int32
      display_name: "Starting Fiscal quarter"
      description: "Select the fiscal quarter for the forecast configuration."
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Q1"
        - value: 1
          label: "Q2"
        - value: 2
          label: "Q3"
        - value: 3
          label: "Q4"
    - name: msdyn_startingfiscalyear
      type: Edm.Int32
      display_name: "Starting Fiscal year"
      description: "Select the fiscal year for the forecast configuration."
      iscomputed: false
      isreadonly: false
      options:
        - value: 10
          label: "FY2028"
        - value: 9
          label: "FY2027"
        - value: 8
          label: "FY2026"
        - value: 7
          label: "FY2025"
        - value: 6
          label: "FY2024"
        - value: 5
          label: "FY2023"
        - value: 4
          label: "FY2022"
        - value: 3
          label: "FY2021"
        - value: 2
          label: "FY2020"
        - value: 1
          label: "FY2019"
        - value: 0
          label: "FY2018"
    - name: msdyn_templatetype
      type: Edm.String
      display_name: "Template type"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the Forecast Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the Forecast Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Draft"
        - value: 2
          label: "In progress"
        - value: 3
          label: "Active"
        - value: 4
          label: "Failed"
        - value: 5
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _ownerid_value
    single_valued_navigation_property:
    - ownerid
    description: "Owner Id"
  - name: _owningbusinessunit_value
    single_valued_navigation_property:
    - owningbusinessunit
    description: "Unique identifier for the business unit that owns the record"
  - name: _owningteam_value
    single_valued_navigation_property:
    - owningteam
    description: "Unique identifier for the team that owns the record."
  - name: _owninguser_value
    single_valued_navigation_property:
    - owninguser
    description: "Unique identifier for the user that owns the record."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_forecastconfiguration_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_forecastconfiguration_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_forecastconfiguration_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_forecastconfiguration_modifiedonbehalfby
  - name: ownerid
    type: Microsoft.Dynamics.CRM.principal
    partner: owner_msdyn_forecastconfiguration
  - name: owningbusinessunit
    type: Microsoft.Dynamics.CRM.businessunit
    partner: business_unit_msdyn_forecastconfiguration
  - name: owningteam
    type: Microsoft.Dynamics.CRM.team
    partner: team_msdyn_forecastconfiguration
  - name: owninguser
    type: Microsoft.Dynamics.CRM.systemuser
    partner: user_msdyn_forecastconfiguration
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_forecastconfiguration_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_forecastconfiguration
  - name: msdyn_forecastconfiguration_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_forecastconfiguration
  - name: msdyn_forecastconfiguration_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_msdyn_forecastconfiguration
  - name: msdyn_forecastconfiguration_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_msdyn_forecastconfiguration
  - name: msdyn_forecastconfiguration_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_forecastconfiguration
  - name: msdyn_forecastconfiguration_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_forecastconfiguration
  - name: msdyn_forecastconfiguration_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_forecastconfiguration
  - name: msdyn_forecastconfiguration_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_forecastconfiguration
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_forecastconfiguration entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.GrantAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.ModifyAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrievePrincipalAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrieveSharedPrincipalsAndAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RevokeAccess
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the msdyn_forecastconfiguration entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdyn_Forecasting
    description: "An extension that helps sales managers and sales people to predict risks in the revenue spotting pipeline."
# There are no remarks for this entity.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex