### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_autocapturesettings
name: "msdyn_autocapturesettings"
type: entitytype
metadata: 
  title: "Microsoft Dataverse EntityType Reference | MicrosoftDocs"
  ms.date: "04/12/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 5f5484e1-b2c8-484c-8d4b-318f3c87402f
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Microsoft Dataverse msdyn_autocapturesettings entitytype."
# This entity doesn't have a description
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_autocapturesettingses"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Auto Capture Settings
  primary_key: msdyn_autocapturesettingsid
  primary_name_attribute: msdyn_name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_autocapture
      type: Edm.Boolean
      display_name: "Auto Capture"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_autocapturesettingsid
      type: Edm.Guid
      display_name: "Auto Capture Settings"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: msdyn_autocapturev1
      type: Edm.Boolean
      display_name: "Auto Capture V1"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_automaticactivityupdate
      type: Edm.Boolean
      display_name: "Automatic Activity Update"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_calendar
      type: Edm.Boolean
      display_name: "Calendar"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_contacts
      type: Edm.Boolean
      display_name: "Contacts"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_defaultassociation
      type: Edm.String
      display_name: "Default Association"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_DontShowSettingStatus
      type: Edm.String
      display_name: "Dont Show dialog Settings for suggestions"
      description: "Dont Show Setting Status for both Suggested activity and Suggested Contact"
      iscomputed: false
      isreadonly: false
    - name: msdyn_emails
      type: Edm.Boolean
      display_name: "Emails"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_meetings
      type: Edm.Boolean
      display_name: "Meetings"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_name
      type: Edm.String
      display_name: "Name"
      description: "The name of the custom entity."
      iscomputed: false
      isreadonly: false
    - name: msdyn_organizationid
      type: Edm.String
      display_name: "Organization Id"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_settingsuiaction
      type: Edm.String
      display_name: "SettingsUI Action"
      description: "SettingsUI Action"
      iscomputed: false
      isreadonly: false
    - name: msdyn_userid
      type: Edm.String
      display_name: "User Id"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_v1termsandconditionscount
      type: Edm.String
      display_name: "V1 TERMS AND CONDITIONS COUNT"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_v2termsandconditionscount
      type: Edm.String
      display_name: "V2 TERMS AND CONDITIONS COUNT"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the Auto Capture Settings"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the Auto Capture Settings"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _ownerid_value
    single_valued_navigation_property:
    - ownerid
    description: "Owner Id"
  - name: _owningbusinessunit_value
    single_valued_navigation_property:
    - owningbusinessunit
    description: "Unique identifier for the business unit that owns the record"
  - name: _owningteam_value
    single_valued_navigation_property:
    - owningteam
    description: "Unique identifier for the team that owns the record."
  - name: _owninguser_value
    single_valued_navigation_property:
    - owninguser
    description: "Unique identifier for the user that owns the record."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_autocapturesettings_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_autocapturesettings_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_autocapturesettings_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_autocapturesettings_modifiedonbehalfby
  - name: ownerid
    type: Microsoft.Dynamics.CRM.principal
    partner: owner_msdyn_autocapturesettings
  - name: owningbusinessunit
    type: Microsoft.Dynamics.CRM.businessunit
    partner: business_unit_msdyn_autocapturesettings
  - name: owningteam
    type: Microsoft.Dynamics.CRM.team
    partner: team_msdyn_autocapturesettings
  - name: owninguser
    type: Microsoft.Dynamics.CRM.systemuser
    partner: user_msdyn_autocapturesettings
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_autocapturesettings_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_autocapturesettings
  - name: msdyn_autocapturesettings_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_autocapturesettings
  - name: msdyn_autocapturesettings_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_msdyn_autocapturesettings
  - name: msdyn_autocapturesettings_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_msdyn_autocapturesettings
  - name: msdyn_autocapturesettings_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_autocapturesettings
  - name: msdyn_autocapturesettings_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_autocapturesettings
  - name: msdyn_autocapturesettings_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_autocapturesettings
  - name: msdyn_autocapturesettings_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_autocapturesettings
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_autocapturesettings entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.GrantAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.ModifyAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrievePrincipalAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrieveSharedPrincipalsAndAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RevokeAccess
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the msdyn_autocapturesettings entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.AutoDataCapture
    description: "Auto Data Capture Feature Description."
# There are no remarks for this entity.
href_see_also:
- text: "Use the Microsoft Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex