### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_playbooktemplate
name: "msdyn_playbooktemplate"
type: entitytype
metadata: 
  title: "Common Data Service EntityType Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: e3e302f3-5430-409a-b08c-7b55d727819f
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Common Data Service msdyn_playbooktemplate entitytype."
description: "Playbook templates contains the definition of the Playbook that helps to standardize a set of best practices or next best actions."
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_playbooktemplates"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Playbook template
  primary_key: msdyn_playbooktemplateid
  primary_name_attribute: msdyn_name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_description
      type: Edm.String
      display_name: "Description"
      description: "Type additional information to describe the playbook template."
      iscomputed: false
      isreadonly: false
    - name: msdyn_estimatedduration
      type: Edm.Int32
      display_name: "Estimated duration (days)"
      description: "Enter the estimated duration in days to indicate the time it may take to complete the playbook template once launched."
      iscomputed: false
      isreadonly: false
    - name: msdyn_fullentitylist
      type: Edm.String
      display_name: "Entities enabled for playbook"
      description: "Internal Use Only"
      iscomputed: false
      isreadonly: false
    - name: msdyn_name
      type: Edm.String
      display_name: "Name"
      description: "Type the name of the playbook template."
      iscomputed: false
      isreadonly: false
    - name: msdyn_playbooktemplateid
      type: Edm.Guid
      display_name: "Playbook template"
      description: "Shows the unique ID of the playbook template."
      iscomputed: false
      isreadonly: false
    - name: msdyn_relatedentitylist
      type: Edm.String
      display_name: "Entities to which a playbook applies"
      description: "Internal Use Only"
      iscomputed: false
      isreadonly: false
    - name: msdyn_trackprogress
      type: Edm.Boolean
      display_name: "Track progress"
      description: "Select whether or not to track the progress of the playbook by creating the activities under a playbook which is in turn linked to the record type the playbook applies to."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the Playbook Template"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Draft"
        - value: 1
          label: "Published"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the Playbook Template"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Draft"
        - value: 2
          label: "Published"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _msdyn_categoryid_value
    single_valued_navigation_property:
    - msdyn_categoryid
    description: "Shows the unique ID of the playbook category associated with the playbook template."
  - name: _ownerid_value
    single_valued_navigation_property:
    - ownerid
    description: "Publisher Id"
  - name: _owningbusinessunit_value
    single_valued_navigation_property:
    - owningbusinessunit
    description: "Unique identifier for the business unit that owns the record"
  - name: _owningteam_value
    single_valued_navigation_property:
    - owningteam
    description: "Unique identifier for the team that owns the record."
  - name: _owninguser_value
    single_valued_navigation_property:
    - owninguser
    description: "Unique identifier for the user that owns the record."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_playbooktemplate_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_playbooktemplate_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_playbooktemplate_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_playbooktemplate_modifiedonbehalfby
  - name: msdyn_categoryid
    type: Microsoft.Dynamics.CRM.msdyn_playbookcategory
    partner: category_playbooktemplate
  - name: ownerid
    type: Microsoft.Dynamics.CRM.principal
    partner: owner_msdyn_playbooktemplate
  - name: owningbusinessunit
    type: Microsoft.Dynamics.CRM.businessunit
    partner: business_unit_msdyn_playbooktemplate
  - name: owningteam
    type: Microsoft.Dynamics.CRM.team
    partner: team_msdyn_playbooktemplate
  - name: owninguser
    type: Microsoft.Dynamics.CRM.systemuser
    partner: user_msdyn_playbooktemplate
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_callablecontext_msdyn_playbooktemplate
    type: Microsoft.Dynamics.CRM.msdyn_callablecontext
    partner: msdyn_callablecontext_msdyn_playbooktemplate
  - name: msdyn_playbooktemplate_Annotations
    type: Microsoft.Dynamics.CRM.annotation
    partner: objectid_msdyn_playbooktemplate
  - name: msdyn_playbooktemplate_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_playbooktemplate
  - name: msdyn_playbooktemplate_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_playbooktemplate
  - name: msdyn_playbooktemplate_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_msdyn_playbooktemplate
  - name: msdyn_playbooktemplate_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_msdyn_playbooktemplate
  - name: msdyn_playbooktemplate_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_playbooktemplate
  - name: msdyn_playbooktemplate_msdyn_playbookactivity
    type: Microsoft.Dynamics.CRM.msdyn_playbookactivity
    partner: msdyn_playbooktemplateid
  - name: msdyn_playbooktemplate_msdyn_playbookinstance
    type: Microsoft.Dynamics.CRM.msdyn_playbookinstance
    partner: msdyn_playbooktemplateid
  - name: msdyn_playbooktemplate_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_playbooktemplate
  - name: msdyn_playbooktemplate_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_playbooktemplate
  - name: msdyn_playbooktemplate_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_playbooktemplate
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_playbooktemplate entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.GrantAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.ModifyAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrievePrincipalAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrieveSharedPrincipalsAndAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RevokeAccess
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the msdyn_playbooktemplate entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdyn_Playbook
    description: "Playbook"
# There are no remarks for this entity.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex