### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_UpdateAutoCaptureSettings
name: "msdyn_UpdateAutoCaptureSettings"
type: action
metadata: 
  title: "Dataverse Action Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 365f18e8-2305-48c4-ae62-9a18e5e224af
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse msdyn_UpdateAutoCaptureSettings Action."
namespace: Microsoft.Dynamics.CRM
# This Action has no description.
owningsolution: Microsoft.Dynamics.CRM.AutoDataCapture
# This action has no bound entities.
isbound: false
parameters:
  description: "Parameters allow for data to be passed to the action."
  parameter_items:
  - name: actiontype
    type: Edm.Int32
    nullable: false
    unicode: true
    description: ""
  - name: dialogtype
    type: Edm.Int32
    nullable: true
    unicode: true
    description: ""
  - name: BusinessProcessFlowId
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
  - name: BusinessProcessFlowInstanceId
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
  - name: ActionStepId
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
return_type:
  description: "The msdyn_UpdateAutoCaptureSettings action returns the following value."
  iscollection: false
  nullable: false
  type: Microsoft.Dynamics.CRM.msdyn_UpdateAutoCaptureSettingsResponse
# This action has no identified unbound entities.
# There are no remarks for this action.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex