### YamlMime:OData
uid: Microsoft.Dynamics.CRM.ValidateAIConfiguration
name: "ValidateAIConfiguration"
type: action
metadata: 
  title: "Dataverse Action Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 6c26a370-f309-463e-ac6b-d53328a6349a
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse ValidateAIConfiguration Action."
namespace: Microsoft.Dynamics.CRM
# This Action has no description.
owningsolution: Microsoft.Dynamics.CRM.System
# This action has no bound entities.
isbound: false
parameters:
  description: "Parameters allow for data to be passed to the action."
  parameter_items:
  - name: version
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
  - name: aiconfigurationId
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
return_type:
  description: "The ValidateAIConfiguration action returns the following value."
  iscollection: false
  nullable: false
  type: Microsoft.Dynamics.CRM.ValidateAIConfigurationResponse
# This action has no identified unbound entities.
# There are no remarks for this action.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex