### YamlMime:OData
uid: Microsoft.Dynamics.CRM.DoesNotContainValues
name: "DoesNotContainValues"
type: queryfunction
metadata: 
  title: "Dataverse DoesNotContainValues Query Function Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: b7aac425-958e-43e1-9d5b-529c18f34dbd
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse DoesNotContainValues Query Function."
namespace: Microsoft.Dynamics.CRM
description: ""
parameters:
  description: "Parameters allow for data to be passed to the query function."
  parameter_items:
  - name: "PropertyName"
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
  - name: "PropertyValues"
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
syntax_example: "?$filter=Microsoft.Dynamics.CRM.DoesNotContainValues(PropertyName=@p1,PropertyValues=@p2)&@p1='name'&@p2=['value','value']"
# There are no remarks for this query function.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex