### YamlMime:OData
uid: Microsoft.Dynamics.CRM.RetrieveEnvironmentVariables
name: "RetrieveEnvironmentVariables"
type: function
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement RetrieveEnvironmentVariables Function Reference | MicrosoftDocs"
  ms.date: "02/10/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 14ae14ff-f3d4-46f1-90b7-8803550c5152
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Common Data Service RetrieveEnvironmentVariables Function."
namespace: Microsoft.Dynamics.CRM
description: ""
iscomposable: false
# This function is not bound to any entities.
isbound: false
parameters:
  description: "Parameters allow for data to be passed to the function."
  parameter_items:
  - name: SchemaNames
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
    iscollection: true
return_type:
  description: "The RetrieveEnvironmentVariables function returns the following value."
  type: Microsoft.Dynamics.CRM.crmbaseentity
  iscollection: true
  nullable: false
entities:
  description: "Use the RetrieveEnvironmentVariables function with this entity type:"
  entity_items:
  - type: Microsoft.Dynamics.CRM.environmentvariabledefinition
    displayName: "Environment Variable Definition"
    description: "Contains information about the settable variable: its type, default value, and etc."
# There are no remarks for this function.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex